export const IpcChannel = {
  listProviders: 'providers:list',
  listPresets: 'providers:presets',
  addProvider: 'providers:add',
  updateProvider: 'providers:update',
  deleteProvider: 'providers:delete',
  enableProvider: 'providers:enable',
  listModels: 'providers:list-models',
  getStatus: 'app:status',
  openDevTools: 'app:devtools',
  windowMinimize: 'window:minimize',
  windowToggleMaximize: 'window:toggle-maximize',
  windowClose: 'window:close',
  windowIsMaximized: 'window:is-maximized',
  windowMaximizedChanged: 'window:maximized-changed',
  changed: 'providers:changed',
  getLocale: 'app:getLocale',
  setLocale: 'app:setLocale',
  getMica: 'app:getMica',
  setMica: 'app:setMica',
  getTheme: 'app:getTheme',
  setTheme: 'app:setTheme',
} as const
